"""empty message

Revision ID: ea8db038ebe9
Revises: 
Create Date: 2025-11-10 08:45:17.479585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea8db038ebe9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artista',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('genero',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('senha', sa.String(length=200), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('musica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('artista_id', sa.Integer(), nullable=False),
    sa.Column('genero_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artista_id'], ['artista.id'], ),
    sa.ForeignKeyConstraint(['genero_id'], ['genero.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_artista',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('artista_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artista_id'], ['artista.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_genero',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('genero_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['genero_id'], ['genero.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_genero')
    op.drop_table('user_artista')
    op.drop_table('musica')
    op.drop_table('user')
    op.drop_table('genero')
    op.drop_table('artista')
    # ### end Alembic commands ###
